version: "3.4"

services:
    app:
        image: node:14
        container_name: cuie-app
        environment:
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            PATH_STATIC: ${PATH_STATIC}
        working_dir: /usr/src/app
        ports:
            - 3000:3000
        volumes:
            - ./nodejs:/usr/src/app
            - ./volumes/app/data:${PATH_STATIC}
        depends_on:
            - db
        command: bash -c "npm install && node app.js"
    db:
        container_name: cuie-db
        build:
            context: ./mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./volumes/database:/var/lib/mysql
        ports:
            - 3306:3306